### ISSUE TITLE
Shouldn't problems appear in the minibuffer when you move your cursor over them?

### ISSUE THREAD

**Issue by hicksy994** [emacs-eclim/emacs-eclim#43]
I have everything set up properly. I can see problems with eclim-problems and fix them with eclim-problems-correct, but when i move my cursor over the highlighted error it doesn't print the error in the minibuffer like I was expecting. Do I need to enable this somehow? Am I not correct in thinking this is the expected behaviour?

**Comment by nloyola** [comment]
I just tried this with the latest version, [Melpa 20170310.900](http://melpa.org/#/eclim), and it works for me. 

You've not provided enough details to adequately diagnose this issue. Please fill out the following information:

## Expected behavior

## Actual behavior

## Steps to reproduce the problem

*This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.*

## Environment & Version information

### package version information

*Include here the version string displayed on the MELPA or MELPA Stable sites:*

### Emacs version

*E.g. 24.5* (use <kbd>M-x emacs-version</kbd> to check it if unsure)

### Operating system

*E.g. Fedora 23, OS X 10.11 "El Capitan", Windows 10, etc*

**Comment by hicksy994** [comment]
## Expected behavior
The problem will appear in the minibuffer/echo area when you move your point on them.

## Actual behavior
Nothing is printed to the minibuffer/echo area.

## Steps to reproduce the problem
+ M-x eclim-mode

+ M-x start-eclimd

+ Move point over a highlighted problem

## Environment & Version information

### package version information

Melpa 20170310.900

### Emacs version

GNU Emacs 25.1.1

### Operating system

Arch Linux

**Comment by nloyola** [comment]
What version of Eclim did you install? The one from this site: http://eclim.org/install.html.

**Comment by hicksy994** [comment]
Technically I got it from the AUR (Arch user repository), but the version is the same, yes.

**Comment by nloyola** [comment]
After you use <kbd>M-x start-eclimd</kbd>, does your `*eclimd*`buffer have a line similar to this?

```
2017-03-16 13:25:01,559 INFO  [org.eclim.eclipse.EclimDaemon] Eclim Server Started on: 127.0.0.1:9091 
```

Sometimes, I have to wait up to a minute for the Eclim server to start.

**Comment by hicksy994** [comment]
Yep that's all fine. Like I said everything else works fine. I can autocomplete with company-emacs-eclim and even see the problems that aren't being displayed if I run eclim-problems.

**Comment by nloyola** [comment]
Have you had it work before? Or, have you just installed the package and are trying it out for the first time?

I just can't figure out why it would not work for you, but work for me. We just committed a bug fix related to symbolic links. Does your project use symbolic links?

Is the Java code you are editing in a Git repository I can clone? Or, can you provide me with a single Java file where the problem occurs?

**Comment by hicksy994** [comment]
I previously used spacemacs, and it worked fine there. Thinking about it I've only tried one project, I wouldn't have thought it would make much difference. It's a university one so I cant link it. I will try making a new project and see if the behaviour still occurs.

**Comment by hicksy994** [comment]
@nloyola Just tried, it happens for even the simplest of projects. (I.E I made a project with 1 class, with just a main method that prints hello world).

**Comment by nloyola** [comment]
Have you tried going into the `*eclim: problems*` buffer, pressing `g` to update the list, and then press the <kbd>Enter</kbd> key when the cursor is on one of the problems? 

![eclim-problems](https://cloud.githubusercontent.com/assets/334607/24017227/c44d16b8-0a54-11e7-9a1d-cb43664242ca.png)

**Comment by hicksy994** [comment]
That takes me to the problem, but still doesn't give me any information about it in the java buffer or the minibuffer.

**Comment by nloyola** [comment]
Hi @hicksy994. A new version has been released to Melpa: [20170317.1328](https://melpa.org/#/eclim). Does it fix the problem?

**Comment by kwvanderlinde** [comment]
@nloyola I have noticed this problem as well, and it still persists for me in the latest version.

**Comment by nloyola** [comment]
@kwvanderlinde does it happen to you when there are no compiled files (no `*.elc` files) for the package?

**Comment by kwvanderlinde** [comment]
@nloyola I've reinstalled the package and it works now.

**Comment by nloyola** [comment]
@hicksy994 do you know how to remove the `*.elc` files? Can you give it a try and see if the error still happens?

**Comment by hicksy994** [comment]
@nloyola Hi, I fixed it by adding these 3 lines to my config:

    (setq help-at-pt-display-when-idle t)
    (setq help-at-pt-timer-delay 0.1)
    (help-at-pt-set-timer)
